# Convention:
#     key = value
# where `key` is a hex glyph id (04x), and `value` is either:
# •   a string (the actual replacement), or
# •   an array of any of:
#     •   string (hex USV and name) (recommended), or just the hex USV
#     •   integer: Unicode scalar value
#     •   "<CCsucc>": the (visually/in glyph order) succeeding consonant cluster. Useful for short-i vowel signs.
#     •   "<CCprec>": the (visually/in glyph order) preceding consonant cluster. Useful for repha.
#
# For example, the following are equivalent:
# 00CA = "न्"
# 00CA = ["0928 DEVANAGARI LETTER NA", "094D DEVANAGARI SIGN VIRAMA"]
# 00CA = ["0928", "094D"]
# 00CA = [0x0928, 0x094D]
# 00CA = [2344, 2381]
# 00CA = ["न", "094D DEVANAGARI SIGN VIRAMA"]
# 00CA = ["न", "094D DEVANAGARI SIGN VIRAMA"]
# etc.

# E.g. वर्णॊं is typeset by using three glyphs, of which the first two correspond to
# 0935 DEVANAGARI LETTER VA and 0923 DEVANAGARI LETTER NNA respectively.
# The third glyph could be indicated as:
# xxxx = ["0930 DEVANAGARI LETTER RA", "094D DEVANAGARI SIGN VIRAMA", "<CCprec>", "094A DEVANAGARI VOWEL SIGN SHORT O", "0902 DEVANAGARI SIGN ANUSVARA"]

# TODO: Alternative for me to consider: Just notate it without the "<CCprec>", and use regex replace to move the RA+VIRAMA?
00CA = "न्"
0231 = ["<succ>", "093F DEVANAGARI VOWEL SIGN I"]
00D7 = "स्"
0114 = "ब्र"
0212 = "ह्म"
0261 = ["0940 DEVANAGARI VOWEL SIGN II"]
01B9 = ["0948 DEVANAGARI VOWEL SIGN AI", "0902 DEVANAGARI SIGN ANUSVARA"]
00B5 = ["0930 DEVANAGARI LETTER RA", "094D DEVANAGARI SIGN VIRAMA", "<CCprec>"]
019E = "रू"
0194 = "हू"
019D = "रु"
